# Theme Settings

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"
title                    : "Harry Jhin's Blog"
title_separator          : "|"
subtitle                 : "개발 일지" # site tagline that appears below site title in masthead
name                     : "Harry Jhin"
description              : "최소한의 시행착오와 반복되는 실수를 막는 블로그"
url                      : "https://jinhyun.blog"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "HarryJhin/harryjhin.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
date_format              : "%Y년 %-m월 %-d일"
words_per_minute         : 200
comments:
  provider               : "giscus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : "R_kgDOG-8U6g" # Shown during giscus setup at https://giscus.app
    category_name        : "Announcements" # Full text name of the category
    category_id          : "DIC_kwDOG-8U6s4COF90" # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : '1' # '1' for enabled (default), '0' for disabled
    theme                : "dark" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search: true
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : "fab73bf4df2f9ba92"
  instant_search         : # false (default), true
# SEO Related
google_site_verification : "a_T4eVx6sv2N6eg-z5dGXpaJ1LOh4VEtEEYHrKx2ZWk"
bing_site_verification   :
naver_site_verification  : "5b57a1b99e2bfd39ef6132ba5a4da5a48c5a2609"
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-3TYEXQTJ2M"
    anonymize_ip         : # true, false (default)

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# 페이지 매김을 사용하는 경우 다음을 사용하여 표시되는 게시물의 양을 변경할 수 있습니다.
paginate: 5
paginate_path: /page:num/
# Ruby가 시간 및 날짜 생성 및 조작을 처리하는 데 사용하는 시간대 환경 변수를 설정합니다. 기본값은 운영체제에서 설정한 현지 시간대입니다.
# 확인: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Seoul

include:
  - _pages

# Site Author
author:
  name   : "Harry Jhin"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Algorithm, Spring Boot, Flutter에 대해 공부하는 늅늅이"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:joojinhyun00@gmail.com
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://jinhyun.blog/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HarryJhin"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# Site Footer
footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/HarryJhin/harryjhin.github.io"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  windows:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "목차"
      toc_sticky: true
      sidebar:
        - nav: sidebar
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: true
      toc: true
      toc_label: "목차"
      toc_sticky: true
      sidebar:
        - nav: sidebar

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
languages_archive:
  type: liquid
  path: /languages/
windows_archive:
  type: liquide
  path: /windows/
powertoys_archive:
  type: liquide
  path: /windows/powertoys/
